In [3]:
import numpy as np

# 0 dan 9 gacha bo‘lgan 1D array yarating
a = np.array([0,1,2,3,4,5,6,7,8,9], dtype=int)

print(a)

[0 1 2 3 4 5 6 7 8 9]


In [7]:
# 3x3 o‘lchamdagi faqat nol (0) dan iborat array yarating.

a = np.zeros(([3, 3]), dtype=int)
print(a)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [8]:
# 2x2 tasodifiy sonli array yarating (0-1 oralig‘ida).

a = np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [9]:
# 1D arraydagi barcha 3 dan katta sonlarni toping.

a = np.array([0,1,2,3,4,5,6,7,8,9], dtype=int)
print(a[a>3])

[4 5 6 7 8 9]


In [15]:
# 1D arraydagi barcha manfiy sonlarni 0 ga o‘zgartiring.
a = np.array([0,1,-2,3,4,-5,6,-7,8,9], dtype=int)
a[a<0] = 0
print(a)

[0 1 0 3 4 0 6 0 8 9]


In [25]:
# Arraydagi maksimal sonning indeksini toping.

a = np.array([0,1,2,3,4,5,6,7,8,9], dtype=int)
b=a.max()
print(a[b])

9


In [10]:
# 4x4 array yarating va diagonaldagi elementlarini ajrating.

a = np.eye(4)
print(a.diagonal())

[1. 1. 1. 1.]


In [7]:
# 10 elementli array yarating va uni teskarisiga aylantiring

a = np.array([0,1,2,3,4,5,6,7,8,9], dtype=int)
print(a[::-1])

[9 8 7 6 5 4 3 2 1 0]


In [19]:
# 3x3 tasodifiy arraydagi har bir ustunning maksimalini toping.
a=np.eye(3, dtype=int)
print(a.max(axis=0))

[1 1 1]


In [22]:
# 1D arraydagi elementlar soni 5 dan kam bo‘lsa `True`, aks holda `False` qaytaring.
a = np.array([0,1,2,3,4,5,6,7,8,9], dtype=int)
print(True if a.size > 0.5 else False)

True


In [27]:
# 5x5 array yaratib, ichidagi elementlarni 1 dan 25 gacha to‘ldiring.
a=np.arange(1, 26, 1)
print(a.reshape(5,5))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [30]:
# Arraydagi juft sonlarni ajrating.
print(a[a%2==0])

[ 2  4  6  8 10 12 14 16 18 20 22 24]


In [32]:
# Ikkita 1D arrayni qo‘shing (element-wise).
print(a + a.copy())

[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48
 50]


In [36]:
# 2D arrayda qator va ustun bo‘yicha yig‘indilarni hisoblang.
print(a.sum())

325


In [39]:
# Arrayni 1D dan 2D formatga o‘tkazing.

a=np.array([1,2,3,4], dtype=int)
print(a.reshape(2,2))

[[1 2]
 [3 4]]


In [86]:
# `np.where` yordamida musbat sonlarni `1`, manfiy sonlarni `-1` ga aylantiring.
arr = np.array([-10, 15, 20, -25, 30])
print(np.where(arr > 0, 1, -1))

[-1  1  1 -1  1]


In [44]:
# Arrayda 0 ni nechta marta ishlatilganini hisoblang.
print(np.count_nonzero(a))

4


In [58]:
# 100 ta tasodifiy son yarating (0–50 orasida) va nechta unikal qiymat borligini toping.
a=np.random.randint(0,50, size=(1,100))
print(len(np.unique(a)))

46


In [73]:
# 2 ta array orasidagi umumiy qiymatlarni toping.
b=np.array(1)
print(np.intersect1d(a, b))

[1]


In [77]:
# Array elementlarini `float` turiga o‘tkazing.
print(a.dtype.name, 'convert to', (a.astype(float)).dtype.name)

int64 convert to float64


In [88]:
# Arrayni 90° ga aylantiring.
print(a.reshape(len(a),1))

[[1]
 [2]
 [3]
 [4]]


In [90]:
# Arrayni `broadcasting` yordamida 2 barobarga oshiring.
print(a*2)

[2 4 6 8]


In [101]:
# 2D arrayni `flatten` qiling.
a=np.random.randint(1,22, size=[2,22])
print(a.flatten())

[ 3  5 18 19  9 21 10 16  6  2  4 17 16 21 21 11 18 19  1 16  8  5  8 13
 21 17  4 19 18 20 19 15 18 21 17  3 18  2  4 13  7  7 16 10]


In [127]:
# 100 ta tasodifiy butun sonlardan iborat arrayda 5 ga karralilarni ajrating.
a=np.random.randint(1,100, size=[1,100])
print(a[a % 5 == 0])

[90 20 30 15 90 40 90 25 15 50 10 95 60 20 25]


In [111]:
# Arrayni ketma-ket 3 tadan bloklarga bo‘ling.
a=np.random.randint(1,99, size=[1,99])
print(a.reshape(3,33))

[[62 18 79 12 37 18 17 44 45 57 21 82 54 65 46 50 49 68 42  1 24  4 71 55
   3 70 92  8 27 80 74 35  8]
 [11 21 59 58 94 74 22 18 58 38 50 41 56 19 57 97 26 83 59 81 47 14 74 17
  56 52 54 26 96 54 38 10 76]
 [30 68 52 69 87 11 80 52 34 17  9 64 78 96 71 18 70 86 46 64 68 53 54 11
  20 26 94 34 23 64 79 53 81]]


In [129]:
# Qaysi indeksdagi qiymatlar 10 dan katta ekanini toping.
arr = np.array([5, 12, 7, 20, 10, 15])
print(np.where(a > 10)[0])

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [133]:
# Arrayni normalizatsiya qiling (0–1 orasiga).
print(np.unique((np.sort(a))))

[ 2  3  4  6  7  8  9 10 13 15 16 17 20 21 24 25 26 28 29 30 31 34 37 40
 41 42 43 46 47 48 49 50 51 52 57 58 60 61 62 64 66 67 68 69 72 74 76 77
 78 81 84 86 87 88 89 90 92 94 95 97 98 99]


In [141]:
# 3x3 arrayda har bir ustunni o‘zining maksimumiga bo‘ling.
a=np.random.randint(1,5, size=[3,3])
print(a/a.max(axis=0))


[[1.   1.   1.  ]
 [0.25 0.75 0.5 ]
 [0.75 0.5  0.75]]


In [143]:
# 5x5 arraydagi har bir qatorning o‘rtachasini toping.
a=np.random.randint(1,25, size=[5,5])
print(a.mean(axis=0))

[14.4 11.8 11.  11.6 11.4]


In [146]:
# Har bir elementini kvadratga ko‘paytiring, lekin `for loop` ishlatmasdan.
print(np.square(a)*a)

[[  343 13824    27  4913   512]
 [ 3375   216  1728  9261  8000]
 [ 3375  1000  1331   512  1331]
 [ 2744    27  1331   512  4096]
 [ 9261  4096  5832    64     8]]
